[server]
data_dir = ./data
temp_dir = ./temp
max_size = 10485760
file_types = png,jpg,jpeg,gif,webp,heic,bmp,tiff
dsn = sqlite://./picup.db
exiftool_path = exiftool

host = *
port = 9906
webui_dir = ./webui
webui_enabled = true
; base_url = http://localhost:5173/
assets_base_path = /assets/images
variants_sequence = preview

; [variant.display]
; type = webp
; args = scale=300:72,crop=300

; [variant.preview]
; type = webp
; args = scale=900:72


; [engine.default]
; name = ffmpeg
; provider = ffmpeg
; path = ffmpeg
