[server]
data_dir = ./data
temp_dir = ./temp
max_size = 10485760
file_types = png,jpg,jpeg,gif,webp,heic,bmp,tiff
dsn = sqlite://./picup.db
exiftool_path = exiftool

host = *
port = 9906
webui_dir = ./webui
webui_enabled = true
assets_base_path = /assets/images
;variants_sequence = preview

[engine.default]
provider = ffmpeg
; path = ffmpeg

; [variant.display]; image that appear in the list item
; args = scale=256:72,crop=300

; [variant.preview]
; args = scale=600:72
